export type PlayerHistory = {
  sitOutCounts: Map<string, number>;
  partnerCounts: Map<string, number>;
  opponentCounts: Map<string, number>;
  lastMetRound: Map<string, number>;
};

function pairKey(a: string, b: string): string {
  return [a, b].sort().join('::');
}

// Derives player-level fairness history purely from match history -- covers rounds
// generated by EITHER the fixed-team (even player count) generator or the dynamic
// (odd player count) generator identically, by expanding each match's two teams into
// their four constituent players. This is what keeps fairness consistent across mode
// switches: a team's sit-out in an even round becomes its two players' sit-out here,
// exactly as if they'd sat out individually. See
// docs/superpowers/specs/2026-08-25-custom-league-odd-player-pairing-design.md.
export function derivePlayerHistory(
  playerIds: string[],
  matches: { round: number; teamAId: string; teamBId: string }[],
  teams: { id: string; player1Id: string; player2Id: string }[],
  beforeRound: number
): PlayerHistory {
  const teamById = new Map(teams.map((t) => [t.id, t]));
  const sitOutCounts = new Map<string, number>(playerIds.map((id) => [id, 0]));
  const partnerCounts = new Map<string, number>();
  const opponentCounts = new Map<string, number>();
  const lastMetRound = new Map<string, number>();

  const relevantMatches = matches.filter((m) => m.round < beforeRound);
  const roundsWithMatches = new Set(relevantMatches.map((m) => m.round));

  for (const round of roundsWithMatches) {
    const playingIds = new Set<string>();
    for (const m of relevantMatches.filter((mm) => mm.round === round)) {
      const teamA = teamById.get(m.teamAId);
      const teamB = teamById.get(m.teamBId);
      if (teamA) {
        playingIds.add(teamA.player1Id);
        playingIds.add(teamA.player2Id);
      }
      if (teamB) {
        playingIds.add(teamB.player1Id);
        playingIds.add(teamB.player2Id);
      }
    }
    for (const id of playerIds) {
      if (!playingIds.has(id)) {
        sitOutCounts.set(id, (sitOutCounts.get(id) ?? 0) + 1);
      }
    }
  }

  for (const m of relevantMatches) {
    const teamA = teamById.get(m.teamAId);
    const teamB = teamById.get(m.teamBId);
    if (!teamA || !teamB) continue;

    for (const [p1, p2] of [
      [teamA.player1Id, teamA.player2Id],
      [teamB.player1Id, teamB.player2Id],
    ] as const) {
      const key = pairKey(p1, p2);
      partnerCounts.set(key, (partnerCounts.get(key) ?? 0) + 1);
      lastMetRound.set(key, Math.max(lastMetRound.get(key) ?? 0, m.round));
    }

    for (const a of [teamA.player1Id, teamA.player2Id]) {
      for (const b of [teamB.player1Id, teamB.player2Id]) {
        const key = pairKey(a, b);
        opponentCounts.set(key, (opponentCounts.get(key) ?? 0) + 1);
        lastMetRound.set(key, Math.max(lastMetRound.get(key) ?? 0, m.round));
      }
    }
  }

  return { sitOutCounts, partnerCounts, opponentCounts, lastMetRound };
}
